### ISSUE TITLE
Refactor variant stores to match compressed variant matrix

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#109]
# TODO

- [x] rename covered variant store
- [x] refactor position of each variant into position vector in compressed variant matrix according to specification
- [x] refactor interface of compressed variant matrix to match the minimum multiset requirements
- [x] make value type compatible with CoveredVariant concept
