### ISSUE TITLE
Refactor JST model to match compressed reference database specification

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#110]
## TODO

- [ ] Provide basic interfaces to implement the search interfaces.
- [ ] Creation from source sequence and initial row count
- [ ] insert a variant specified with three parameters: source position, alternate_allele, haplotype indices.

## More specification needed
- [ ] How to handle collisions during insertion? there is at least one ambiguous variant pair, i.e. the same reference allele is modified by at least two alternate alleles coming from the same haplotype. How to find overlaps efficiently? Express this mathematically.
- [ ] How to handle different insertion strategies? Like adding a sequence to the sequence store via a proxy interface or adding a sequence in form of a list of alternate alleles?
- [ ] Is the source sequence exchangeable? 
- [ ] What kind of operations do we expect on the source sequence?
- [ ] To which extend is the coverage type configurable by the client?
- [ ]  Is the source sequence aggregate or composite attribute?
- [ ] We need better concept for coverage design.
