### ISSUE TITLE
Supporting more efficient implementations for basic alternate alleles. 

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#121]
## TODO

- [ ] add dedicated snv store storing SNV in a packed format
- [ ] add dedicated deletion type which works for forward and bidirectional traversal
- [ ] add simple insertion type without recursive definition of variants inside the insertion

## Open questions

- [ ] How to determine the type of the source position?
