### ISSUE TITLE
Migrate the journal sequence tree from SeqAn2 to SeqAn3.

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#19]
Store sequences in JST using a referential compressed delta map, i.e. the memory footprint of storing similar sequences is reduced and only depends on the total number of unique delta operations required to reconstruct each stored sequence. 

###  Acceptance criteria

- [x] When traversing the compressed JST every unique context is accessible exactly once
- [x] When the context size is 0 and the respective context is empty, the traversal is still valid but only produces empty contexts
- [x] negative context sizes lead to undefined behavior and are only asserted and documented
- [x] infinity large context sizes represent each complete sequence 
- [x] the context position represents the correct position for every sequence that shares this context
- [x] when all sequences are identical only one context is represented for every sequence
- [x] when all sequences do not share any common delta operation, then all sequence contexts must be explored only generating a single position vector as output.
- [x] different delta operations can be locate on the same reference position. 

### Tasks

- [x] create a delta map with a variant type
- [x] the variant type can either represent a substitution, deletion or insertion
- [x] a delta operation is a tuple with the following data: 
       * reference position: the position in the reference sequence where this delta operation applies to
       * sequence coverage: a bit vector representing all sequences that have this delta operation in common (sdsl::int_vector<int64_t>)
       * a pointer to the inserted sequences or a size denoting the number of deleted characters compared to the reference 
- [x] the variant map is sorted by the reference anchor position of each delta operation (we make this a separate data structure to test it properly)
- [x] test and document the variant map
- [ ] replace the std::vector in the JST with the delta map implementation
- [x] the delta map is constructed from the alignment, if a new sequence is added the bit vector is resized and updated with the respective positions
- [x] translate an alignment into a set of delta operations and make a bulk insert, i.e. we can parallelize updating the jst
- [x] adapt the traversal to traverse every distinct context only and return a slice over the current journal sequence decorator
