### ISSUE TITLE
Alignment with vectorisation

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#3]
Complete the vectorised alignment variants listed below for the thesis, including proper testing, benchmarking using micro-benchmarks as well as macro-benchmarks and comparison to other libraries. The focus of the thesis is generalisability and extensibility rather than best performance, albeit it should  be expected that the peak performance is high.

See https://github.com/rrahn/seqan3/tree/master-alignment for reference implementation.

### Open todos:

- [ ] trace computation
- [ ] cache oblivious trace computation
- [ ] trace pointer with subsequent trace computation from trace regions
- [ ] local alignment - all operations
- [ ] analyse cache efficiency (trace version and scoring matrix version)
- [ ] 8-bit saturated mode
- [ ] protein profile scoring scheme 
- [ ] 8-bit protein scoring scheme with gather
- [ ] AVX512 support - automated testing with AVX512?
- [ ] Extension for other vector extensions

### Comparison to other libraries

- [ ] parasail
- [ ] ksw2
- [ ] edlib
- [ ] paraband
- [ ] wfa-alignment
- [ ] GPU: Gasal, NVBIO, CUDASW? -> should be at least mentioned.
- [ ] FPGA solutions?
- [ ] XeonPhi solutions?
