### ISSUE TITLE
Create jst iterator that outputs only the current visited element instead of each context.

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#30]
Add a stack notification method to allow algorithms to register via a stack listener interface to the JST traversal. Then instead of  rerunning the algorithm on every context, the algorithm takes care of its own stack to track the branch events. For example stateful algorithms can push/pop the state from there own stack.

### Tasks

- [x] Provide a concept for algorithms to register at the traversal
- [x] Implement type erased registration process to a dedicated JST traversal agent.
- [x] The returned traversal agent is a flat input range.
- [x] When a new branch is created the registered algorithms are notified with a push event.
- [x] When a branch is removed the registered algorithms are notified with a pop event.
- [x] The algorithm is applied on the full range and acts as if it is a flat range by maintaining its own state stack to resume to early points in the iteration.
- [x] Refactor the core traversal of the current context enumerator to allow different agents use the traversal differently.

### Idea

* Increment iterator -> on_push -> store state on stack
* algorithm updates always state on top of the stack -> always the last active one.
* make this a generic implementation that uses CPOs in order to allow users to overwrite certain behaviours for their particular algorithms.
