### ISSUE TITLE
Simulate Alignments for journal sequence creation

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#32]
To test the mapping application independent of the jst creation an alignment simulator should be added. This simulator gets a sequence and some parameters to vary the differences between the aligned sequences. From the simulated alignments a sequence 

### Tasks
* Add a sub-command parser 'simulate' which allows to simulate the sequence alignments
   * Create a top-level sub-directory jstmap-simulate (e.g. copy from jstmap-index and replace all occurrences of index with simulate in all files.)
   * Register the new sub-command in the top-level CMakeLists.txt by adding `add_subdirectory (jstmap-simulate)` in the Application section: https://github.com/rrahn/jstmap/blob/19bf25cb74982bc4379d12cdb069e7292fbacb55/CMakeLists.txt#L40
   * Link against the new simulate target in the main applications CMakeLists.txt https://github.com/rrahn/jstmap/blob/19bf25cb74982bc4379d12cdb069e7292fbacb55/jstmap/CMakeLists.txt#L5-L6 by adding jstmap::simulate
   * In the main.cpp https://github.com/rrahn/jstmap/blob/19bf25cb74982bc4379d12cdb069e7292fbacb55/jstmap/jstmap/main.cpp#L24 add a new tool name for the simulate sub-command and register it in the argument parser https://github.com/rrahn/jstmap/blob/19bf25cb74982bc4379d12cdb069e7292fbacb55/jstmap/jstmap/main.cpp#L37-L38
   * Enable the switch to the new sub-command when the simulate tool is called by the user: https://github.com/rrahn/jstmap/blob/19bf25cb74982bc4379d12cdb069e7292fbacb55/jstmap/jstmap/main.cpp#L50-L55
* Input is a reference sequence, e.g. chr 22 of the human genome or simply a simulated sequence (to easily test smaller genome sizes as well)
* Simulation parameter: percentage total difference (later some parameters to vary indels and substitution lengths)
  *  At the beginning we simply use an uniform distribution of the event location in the reference sequence
  * The proportion of Substitutions vs InDels should be 0.5/0.25/0.25, i.e. 50% of all differences are substitutions (SNPs at the beginning) and 25% are insertions and 25% are deletions.
  * The simulated alignments need to model a pair of [seqan3::aligned_sequence](http://docs.seqan.de/seqan/3-master-user/interfaceseqan3_1_1aligned__sequence.html), which can be modeled as:
  ```cpp
      using aligned_sequence_t = std::vector<seqan3::gapped<char>>;
      using alignment_t = std::pair<aligned_sequence_t, aligned_sequence_t>; 
  ```
   For the `aligned_sequence_t` there is then a dedicated API to insert gaps, which allows to create the alignment manually.
* The sub-command parser outputs the simulated jst.
* To test the general API it is sufficient to start with a unit test of the respective simulate functions:
   * Add a new sub-directory in the respective test folder: https://github.com/rrahn/jstmap/tree/master/test/api/jstmap 
   * Best would be to copy one of the existing directories and adapt the namings, includes etc.
   * Let Cmake know about the new directory here: https://github.com/rrahn/jstmap/blob/19bf25cb74982bc4379d12cdb069e7292fbacb55/test/api/jstmap/CMakeLists.txt#L2
   * hint: try to run and build the test as early as possible
      * run `cmake .` in the top-level build directory (there is a cmake cache generated so you don't need to repeatedly call the entire cmake command) (this only needs to be done whenever a new cmake file was added or a new test was added to the cmake file, since the new test needs to be configured as well).
      * Go into `test/api/jstmap/simulate` and call `make <target_name>` or just `make` to build all test targets in this directory.
      * Run `ctest --output-on-failure` to execute the tests and see the error in case the unit test fails, or you can also just run the binary in that directory: `./<test_name>`

### Acceptance criteria

- [x] The generated sequence must have exactly `ceil(error_rate * |ref|)` many variants.
- [x] The aligned reference sequence must be identical to the original reference sequence when stripping away the gaps.
- [ ] For a given position there must be a change in the target sequence, i.e. the base is not replaced with the same base.
- [x] When the error rate is 0 nothing should be changed. 
- [x] When the error rate is negative or the above 1 then an exception is issued informing about an invalid input: `std::invalid_argument`
- [x] When the reference is empty an exceptions is issued informing about an invalid input.
- [ ] There should be no overlapping or nested substitutions/deletions.
- [ ] Simulated variants such that they always have one position in between.
- [ ] Repeat drawing a variant at most 100 times in order to avoid infinite runs. Raise an exception `std::runtime_error` should break with an exception if this is not possible.

### Done

- [x] Code 
- [x] Tests
- [ ] Documentation
- [x] Reviewed
