### ISSUE TITLE
Context Traversal for substitutions

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#33]
### Task
* Extend the traversal to work with substitutions.

### Acceptance criteria
- [x] substitution is at the end
- [x] substitution is at the beginning
- [x] multiple substitutions for one sequence
- [x] the entire reference is substituted
- [x] substitution such that exactly one context exists
- [x] substitution overlap 

### DoD

- [ ] Code
- [ ] Test
- [ ] Document
- [ ] Review
