### ISSUE TITLE
Context Traversal for insertions

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#34]
The traversal should be able to explore all contexts if the delta events are insertions.

### Task
* Extend the traversal to work with insertions.

### Acceptance criteria
- [x] insertion is at the end
- [x] insertion is at the beginning
- [x] multiple insertions for one sequence
- [x] a sequence is inserted in an empty reference sequence 
- [x] insertion such that exactly one context exists
- [x] insertion overlap 

### DoD

- [ ] Code
- [ ] Test
- [ ] Document
- [ ] Review
