### ISSUE TITLE
Context Traversal for deletions

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#35]
The traversal should be able to explore all contexts if the delta events are deletions.

### Task
* Extend the traversal to work with deletions

### Acceptance criteria
- [x] Deletion is at the end
- [x] Deletion is at the beginning
- [x] Multiple deletions for one sequence
- [x] All sequences are deleted completely 
- [x] Deletion such that exactly one context exists
- [x] Deletion overlap 
- [x] multiple deletions at the beginning
- [x] multiple deletions at the end
- [x] deletion within the first context positions but not the begin
- [x] nested deletions

### DoD

- [ ] Code
- [ ] Test
- [ ] Document
- [ ] Review
