### ISSUE TITLE
Context traversal for mixed delta events

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#36]
### Task
* Extend the traversal to work with mixed delta events

### Acceptance criteria
- [x] Fuzzy testing that adds randomly some valid delta events  => depends on  alignment simulator is available.
- [x] Insertion at begin followed by deletion of entire sequence, i.e. no valid context exists (insertion is smaller than context size)
- [x] Insertion at begin followed by deletion of entire sequence except last one, i.e. one valid context exists through insertion
- [x] Insertion at begin followed by split deletions, i.e. one valid context exists through insertion and multiple deletions
- [x] Insertion at begin and deletion at begin: `[1, 1, 0, 0]` & `[1, 0, 1, 0]`
- [x] Substitution at begin and deletion at begin: `[1, 1, 0, 0]` & `[1, 0, 1, 0]`
- [x] Insertion, substitution and deletion at begin: `[1, 1, 1, 1, 0, 0, 0, 0]` & `[1, 1, 0, 0, 1, 1, 0, 0]` & `[1, 0, 1, 0, 1, 0, 1, 0]`
- [x] deletion followed by insertion, i.e. a shortened sequence is extended by the insertion and still valid: `[1, 0, 0, 1]` & `[0, 0, 1, 1]`
- [x] deletion and substitution followed by insertion at end
- [x] deletion, insertion, deletion such that one valid context exists

### DoD

- [x] Code
- [x] Test
- [x] Document
- [x] Review
