### ISSUE TITLE
Application wide logger

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#38]
For the application we might want to log different levels of information depending on build type and user specified verbosity level. 
For this we need a logger mechanism that allows to enable/disable certain logging information on configuration/compile time and on runtime.

Here are some notes about logging mechanisms: https://quuxplusone.github.io/blog/2020/02/12/source-location/

### Task
- [ ] Make the logger a singleton like std::cout
- [ ] The logger should be able to print different log level information
- [ ] The logger should allow to print different verbosity information based on the runtime parameter given.
- [ ] set to the cerr to separate the regular output from the logging output
