### ISSUE TITLE
Alignment with multi-threading

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#4]
Implement and finish the section about generic multi-threading, including proper testing and macro-benchmarks on large systems and compare them to other solutions of other libraries. Focus on the design and the generic aspect. Include the part of the unified executor proposal and how to derive the design for this. Design aspects of exchanging the executor and get different behavior. Naming, omp_executor and wavefront-executor.

### Todos

- [ ] design task based execution 
- [ ] design async buffer
- [ ] design execution interface from outside (what about offloading)
- [ ] async execution of multiple sequences
- [ ] implement generic wavefront model - [see](https://github.com/rrahn/seqan3/tree/wavefront_alignment-unified-executor)
- [ ] adapt global alignment
- [ ] adapt semi-global alignment
- [ ] adapt local alignment
- [ ] special banded version along blocks
- [ ] add vectorised trace-pointer version for alignment
- [ ] comparison: long sequence alignment
- [ ] comparison: long read alignment + pre-filtering using k-mers
