### ISSUE TITLE
Initial just-map setup

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#5]
Establish an intial tool setup that performs the basic operations and provides the necessary scaffold to implement the major features for the tool in an incremental step.

### Acceptance criteria

- [x] The application template is created and can be used in production.
- [x] A subcommand index exists that converts a set of reference sequences into a journal string tree, which can be saved and loaded from disk
- [x] A subcommand map exists that gets the journal string tree as well as a set of single-end short reads and maps/aligns the reads to the references in the journal string tree and outputs a bam file per reference sequence with the alignment information
- [x] The mapper finds all locations with 0 errors.

### Tasks

- [x] setup the application template - follow: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1204r0.html
- [x] provide two sub-tools: one for the index creation and one for the mapping process.
- [x] the journal string tree can be serialised and deserialised and is self-contained. This means that the reference sequence is part of the data structure at the moment.
- [x] the journal string tree is only a vector of sequences at the moment (examples should be kept small)
- [x] the mapper reads in a sequence file of short-reads and maps them against the reference sequences of the journal string tree.
- [x] generates a bam file for the mapped reads.
- [ ] establish a set of CLI tests that provide accurate mapping positions -> we assume that the method is exact by comparing against an existing output file which can be generated by an existing mapper.
- [ ] use a reference set for testing:
    * sample 10 genomes from chr22
    * sample 1K reads of length 100bp from original chr22
    * use original genome as reference to ensure all hits are found
