### ISSUE TITLE
Get a specific sequence from the journal sequence tree

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#50]
Accessing a particular stored sequence from the journal string tree allows to generate benchmark samples for the performance analysis.

### Tasks

- [ ] Add a `sequence_at(size_t index) -> journal_decorator_type`   interface to the JST, which returns a journal decorator for the target sequence at `index`.
- [ ] The index must be >0 and < `size()`. Throw an invalid argument exception if this is not the case.
- [ ] test the correctness of the generation.
