### ISSUE TITLE
Sample reads for performance analysis

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#51]
Add a sampling tool to the application which samples sequences from a given journal sequence tree. 
Allow to set the number of sampled reads as well the length of the 

### Tasks

- [x] add tool to view haplotypes of the given jst.
- [x] generate sample fastq file with mason simulator including the output of an alignment file to validate the search with.
- [x] adapt search to read in a fastq file
