### ISSUE TITLE
Performance benchmark to compare JST based search vs naïve search.

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#52]
Add a performance benchmark which compares the runtime of the JST based search with the runtime of the naïve search to further track performance improvements in the data structure. 

### Tasks

- [x] only focus on exact search at the moment
- [x] refactor jst search to apply naïve search on it from the benchmark as well (needs later no adaption)
- [x] implement naïve search which sequentially iterates over each sequence.
- [x] execute and compare the benchmark and document current results.
- [x] setup google benchmark run in application template.
- [x] validate the results.
