### ISSUE TITLE
Validating mapping results.

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#53]
Add a validation tool in the jstutil program setup to compare and validate two generated BAM-files. This allows to compare whether the results generated by the mapper are exact. Also validate the results against other applications as well.

### Tasks:

- [ ] Validate that the header is correct (same set of reference sequences)
- [ ] Output #of different records in either file
- [ ] Allow more verbose output to see which records are not found
- [ ] Check if all records really exist in the reference sequences (check that context generation is correct)
