### ISSUE TITLE
Output a sam file with the more complete information.

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#55]
Output a sam file that contains the mapping locations of the read in the reference sequences and the mapping qualities.

### Tasks

- [x] Refine the sam file output to output all mapping locations
- [x] sam header: SQ field with SN and LN fields per reference
- [x] reference id 
- [x] q_name
- [x] mapping position
- [x] mapping quality -> set to 255
- [ ] Cleanup
- [ ] Create annotation file for jst at the beginning of search (later do it only if not present)
- [ ] Create query annotation store and handle optional qualities
