### ISSUE TITLE
Add a JST partitioning structure for the IBF indexing

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#56]
Add a partitioned JST structure that allows to jump to specific locations and start/resume the search from this location.
The JST is split into bins. The IBF can then be constructed over the k-mers of each bin. Later the IBF query will give all bins that might contain potential candidates for the search. The search algorithm then loads the enumerator from the given bin and applies the search in this JST section.

### Tasks

- [x] Add a partitioned JST: `journal_sequence_tree_partitioned`
- [x] The partitioning data structure is lightweight, such that references exactly one JST
- [x] is constructed with a bin count and then splits the JST in that many bins
- [x] bin size depends on the size of the reference sequence: `bin size = |reference| / #bins`
- [x] Each bin is represented by a snapshot of a context enumerator that points to the begin of the respective section
- [x] There is a subscript operator which returns a copy of the enumerator for that particular bin. Allowed are unsigned integers in the range `[0, #bins)`
- [x] Querying and iterating the same enumerator will always result in the same traversal (is deterministic)
- [x] The partitioned JST can be serialised to/from disk
- [ ] Adapt the search to load the partitioned IBF and step through the bins iteratively without filtering.

### Notes about the search:
- [ ] The index subcommand currently has as input the vcf file, a fasta file and the output of the jst.
- [ ] The subcommand will be updated with a section for the partitioning. This contains a parameter to select the bin count. 
- [ ] By default the bin count is set to 1.
- [ ] The serialisation method is updated to always write out a partitioned JST (first the original JST and then the partitioned JST wrapper).
- [ ] The search is adapted to deserialise the combined archive (first the jst, and then the partitioned jst)
- [ ]  Then the search method will be adapted to work on the partitioned JST.

```cpp
cereal::BinaryOutputArchive arch{output_path};
jst.save(arch);
pjst.save(arch);

// ... 

cereal::BinaryInputArchive arch{input_path};
jst.load(arch);
libjst::journal_sequence_tree_partitioned pjst{std::addressof(jst)};
pjst.load(arch);
```

### Refactoring

Separate the model from the behaviour.
```cpp
class journal_sequence_tree_traverser_model
{
   // only construction, and just the model
};

class journal_sequence_tree_traverser_base<derived_t jst_t> : protected journal_sequence_tree_traverser_model
{

   context_enumerator(journal_sequence_tree_traverser_model const & model, size_t const context_size) : base_t{model} 
   {
        // access model structures.
        // serialise model only.
   }
};

```
* step 1: context size independent construction of traverser objects (no context size, no branch initialisations)
* step 2: create context enumerator/range_agent from traverser object and context size including initialisation

Solved by splitting traversal and traverser model. The model can be constructed independent of the context size and the traverser is initialised to the begin of a new bin with a dedicated context size. This means that once constructed the partitioned JST can be executed with any context size dynamically.

### Done

- [x] Code
- [x] Test
- [x] Doc
- [x] Review
