### ISSUE TITLE
Refine search with partitioned JST with prepended IBF structure and serialise to disk

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#57]
Construct an IBF over the partitioned JST to allow a a pre-filtering step during the search in order to reduce the search time to a fraction of the original search. There should be a single file output that contains both the partitioned JST and the associated IBF.
This makes it easier to maintain and store/load the index structure as a whole.

### Tasks

- [ ] Include the construction of the IBF. 
- [ ] Add a wrapper class that combines the IBF and the partitioned JST for easier handling of the serialisation.
- [ ] Investigate whether the IBF construction must be adapted to handle the bins of the partitioned IBF.
- [ ] The user can select a k-mer length. Default is 19. Must be in the interval [14, 32) for dna4, and less for larger alphabets.
- [ ] Serialise the entire data structure to/from the disk
- [ ] Adapt the search to split the query into k-mers and locate all bins that are withing a precomputed counting threshold.
- [ ] Only apply the search to those sections that are given by the IBF filtering step.
