### ISSUE TITLE
Vectorised bit vector operations

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#61]
Speedup the traversal by vectorising the bit vector operations. 

### Tasks

- [x] Add a bit vector implementation that supports bitwise operations on the underlying words.
- [x] All bits that are not used at the end are always set to 0.
- [x] Add an iterator that iterates over the bits and allows to set bits. -> return a proxy.
- [x] Write strong loops that allow for auto-vectorisation (openMP simd?)
- [x] The bit vector shall model AllocatorAwareContainer
- [x] compare the runtime -> investigate whether we need explicit vectorisation.
