### ISSUE TITLE
Update the readme

### ISSUE THREAD

**Issue by rrahn** [rrahn/jstmap#62]
### ToDo

- [ ] Add a proper installation guide
- [ ] Add correct license file
- [ ] Add benchmark results
- [ ] add status tags
